name: Release
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.release.tag_name }}
      - name: Install deps
        run: npm ci
      - uses: JasonEtco/build-and-tag-action@v2
0        env:
          GITHUB_TOKEN: ${{ github.token }}